### ISSUE TITLE
CFD口座振替画面新規開発

### ISSUE THREAD

**Issue by TakahiroHyodo** [AppDevTeam-work/ScalaRichCfd#1]
###CFDプロジェクト概要
https://lion-fx.atlassian.net/wiki/spaces/CFD/overview
接続先情報
https://lion-fx.atlassian.net/wiki/spaces/CFD/pages/91816325/CFD+API

###概要
FX-CFD間の資金振替を行う画面
IIJ-API(旧バージョン)
https://docs.google.com/spreadsheets/d/1MsREOc4FZyynyfN-jPVuJ6YnRaPB68ZH

IIJ-API(新バージョン：6/21にSTGリリース予定)
https://docs.google.com/spreadsheets/d/1kB00GSI-B4qesBUMuBpaHHd83G3BQcC4/

###画面仕様書
https://docs.google.com/document/d/1qnr7ZWav6sxfuM7cr6AirLI3Gu05FFzfwvUPtweE4aE

**Comment by t-matsushita1108** [comment]
画面開発完了＋マージ済のためクローズします。
